import meta from './meta.json';
import { state,filtered,page,points,ref,STAMP,uid,task } from './state';
import type { Row } from './seed';
import { reportFile } from './export-file';

export function report(type:string,q:Row={}) {
  const members=filtered(state.members,q),masters=filtered(state.stationMasters,q),pools=filtered(state.pools,q);
  const blank=()=>Object.fromEntries(meta.metrics.map(k=>[k,/count$/i.test(k)?'0':/Rate|Share$/.test(k)?'0.00':'0.00']));
  let items:Row[]=[];
  if(type==='AI_POOLS')items=pools.map(p=>({dimensions:{poolIssueId:p.id,project:ref(state.projects.find((x:Row)=>x.id===p.projectId)),lottery:ref(state.catalog.lotteries.find((l:Row)=>l.id===p.lotteryId)),play:{id:p.playId,code:'FC3D_STRAIGHT',name:'福彩3D直选'},projectId:p.projectId,issueCode:p.issueCode,status:p.status,settlementStatus:p.status,settlementMode:p.settlementMode,disclosureStatus:p.numbersDisclosed?'PUBLISHED':'PENDING',drawVersion:p.status==='OPEN'?null:'1',drawNumbers:p.status==='OPEN'?null:'2 5 8',winningNumberCode:p.status==='OPEN'?null:'258',exceptionReason:p.status==='EXCEPTION_PENDING'?'演示待处理异常':null},metrics:{...blank(),issueCount:'1',participantCount:String(p.participantCount),participationPersonTimes:String(p.participantCount),combinationCount:'50',totalPurchasePoints:p.totalPurchasePoints,netEffectivePurchasePoints:p.totalPurchasePoints,userPurchasePoints:p.userPurchasePoints,platformPoints:p.platformPoints,actualUserShare:p.actualUserShare,totalWinningPoints:p.totalWinningPoints||'0.00',userWinningPoints:p.userWinningPoints||'0.00',postedUserWinningPoints:p.status==='SETTLED'?p.userWinningPoints:'0.00',platformWinningPoints:p.totalWinningPoints?points(Number(p.totalWinningPoints)-Number(p.userWinningPoints)):'0.00',rewardRequiredPoints:p.totalWinningPoints||'0.00',targetRoundingAdjustmentPoints:'0.00',actualNetReturnRate:p.totalWinningPoints?'0.10':'0.00',requestedTargetNetReturnRate:String((state.allocations.filter((a:Row)=>a.poolIssueId===p.id&&a.status!=='SUPERSEDED').at(-1)?.requestedTargetNetReturnPercent??p.defaultTargetNetReturnPercent)/100),differencePercentagePoints:p.status==='OPEN'?null:'0.00',winningNotReadyCount:p.status==='EXCEPTION_PENDING'?'1':'0'}}));
  else if(type==='STATION_MASTERS')items=masters.map(m=>({dimensions:{date:'2026-10-03',station:m.station,stationMaster:ref(m)},metrics:{...blank(),openingBalancePoints:points(Number(m.disposablePoints)-1000),periodGrantedPoints:'1000.00',periodDeductedPoints:'0.00',memberGrantedPoints:m.grantedMemberPoints,memberDeductedPoints:m.deductedMemberPoints,endingBalancePoints:m.disposablePoints}}));
  else if(type==='LEDGER_RECONCILIATION'){const balance=points(state.budgets.reduce((s:number,b:Row)=>s+Number(b.availablePoints),0)+state.members.reduce((s:number,m:Row)=>s+Number(m.wallet.availablePoints)+Number(m.wallet.reservedPoints),0)+state.stationMasters.reduce((s:number,m:Row)=>s+Number(m.disposablePoints),0));items=[{dimensions:{date:'2026-10-03',settlementStatus:'MATCHED',exceptionReason:null},metrics:{expectedPoints:balance,postedPoints:balance,differencePoints:'0.00',mismatchAccountCount:'0'}}];}
  else items=members.map(m=>({dimensions:{date:'2026-10-03',station:m.scope.station,stationMaster:m.scope.stationMaster,member:ref(m),vipLevel:{id:m.vipName,name:m.vipName,code:m.vipName},referralLevel:{id:m.referralName,name:m.referralName,code:m.referralName},fixedRewardPolicyVersion:state.referral.fixedRewardPolicyVersion,aiSharePolicyVersion:state.referral.aiSharePolicyVersion},metrics:{...blank(),memberCount:'1',newMemberCount:'1',periodGrantedPoints:m.qualifiedRechargePoints,periodDeductedPoints:m.stationDeductedPoints,netGrantedPoints:points(Number(m.qualifiedRechargePoints)-Number(m.stationDeductedPoints)),availablePoints:m.wallet.availablePoints,reservedPoints:m.wallet.reservedPoints,settledStakePoints:m.totalBetPoints,totalWinningPoints:points(Number(m.totalBetPoints)+Number(m.netProfitPoints)),netProfitPoints:m.netProfitPoints,directMemberCount:String(m.directMemberCount),directAvailablePoints:m.directMemberAvailableTotal,rechargeMemberCount:'1',rechargeCount:'1',deductMemberCount:'1',deductCount:'1',qualifiedRechargePoints:m.qualifiedRechargePoints,vipBaseLimit:m.quota.vipBaseLimit,vipBaseLimitPerMember:m.quota.vipBaseLimit,referralExtraLimit:m.quota.referralExtraLimit,totalQuotaLimit:m.quota.totalLimit,quotaUsedPoints:m.quota.usedPoints,quotaRemainingPoints:m.quota.remainingPoints,quotaUsageRate:points(Number(m.quota.usedPoints)/Number(m.quota.totalLimit)),memberShare:points(1/Math.max(members.length,1)),validMemberCount:String(m.directMemberCount),validRate:'1.00',eligibilityStatus:'READY'}}));
  if((q.from&&new Date(q.from.length===10?q.from+'T00:00:00+08:00':q.from).getTime()>new Date(STAMP).getTime())||(q.to&&new Date(q.to.length===10?q.to+'T23:59:59+08:00':q.to).getTime()<new Date('2026-10-01T00:00:00+08:00').getTime()))items=[];
  const totals:Row={};for(const row of items)for(const [key,value] of Object.entries(row.metrics)){if(!Number.isFinite(Number(value)))continue;totals[key]=points(Number(totals[key]||0)+Number(value));}
  for(const key of Object.keys(totals)){if(/Count$/.test(key))totals[key]=String(Number(totals[key]));if(/Rate|Share$/.test(key))totals[key]=items.length?points(Number(totals[key])/items.length):'0.00';}
  return {...page(items),reportType:type,metricDictionaryVersion:'DEMO-1',filters:{from:q.from||'2026-09-27',to:q.to||'2026-10-03',...q},asOf:STAMP,projectionVersion:'1',sourceWatermark:'demo-ledger-1',totals,totalScope:'FULL_FILTER',complete:true};
}
export function exportReport(body:Row){
  const id=uid('export'),data=report(body.reportType,body.filters||{});
  const keys=[...new Set(data.items.flatMap((r:Row)=>[...Object.keys(r.dimensions),...Object.keys(r.metrics)]))] as string[];
  const cell=(value:any)=>typeof value==='object'&&value!==null?value.name||JSON.stringify(value):String(value??'');
  const rows=[keys,...data.items.map((r:Row)=>keys.map(key=>cell(r.dimensions[key]??r.metrics[key])))];
  state.exports[id]={id,status:'COMPLETED',rowCount:String(data.items.length),downloadUrl:null,expiresAt:'2099-01-01T00:00:00Z',rows,format:body.format||'CSV'};
  return task('REPORT_EXPORT',`/api/admin/v1/report-exports/${id}`);
}
export function getExport(id:string){
  const item=state.exports[id];if(!item)throw new Error('演示导出不存在');
  return {...item,downloadUrl:URL.createObjectURL(reportFile(item.rows,item.format))+`#运营报表.${item.format.toLowerCase()}`};
}
