import type { ReportColumn, ReportDefinition } from './report-config';
export type ManagementKind = 'daily' | 'stationBusiness' | 'budgetFlows' | 'reconciliations' | 'exceptions' | 'aiBusiness';
const c = (key:string,label:string,format?:ReportColumn['format'],help?:string):ReportColumn => ({key,label,format,help});
const amount = (key:string,label:string,help:string) => c(key,label,'money',help);
const common = ['所有金额为虚拟积分；汇总与导出覆盖完整筛选结果，分页不改变统计。', '历史记录缺失显示未记录。报表不把部分演示账本当作完整历史，不用当前余额反推期初、期末。'];
export const managementDefinitions: Record<ManagementKind,ReportDefinition> = {
 daily: {name:'经营日报(新增)',href:'/reports/business-daily',pageId:'A31',purpose:'每天查看各站点的参与规模、加减分、返还和奖励，点击详情追溯组成记录。',
  business:['按业务实际发生日汇总：加减分取交易时间，认购取认购时间，退款取退款时间，普通有效投注与净输赢取完成结算时间，奖励取实际发放/回收时间。',
   '参与人数按会员去重；普通有效投注只计已结算未退款订单。AI参与积分按认购减退款，返还包含本金；不把会员加分或平台预算追加叫作经营收入。',...common],
  columns:[c('reportDay','日期'),c('stationName','所属站点'),c('stationMasterName','所属站长'),c('activeCount','参与会员数',undefined,'当日存在普通下单或AI认购的去重会员数。'),
   amount('granted','会员加分净额','站长加分减对应冲正，按交易发生日统计。'),amount('deducted','会员减分净额','站长减分减对应冲正。'),
   amount('ordinaryPurchase','普通下单积分','下单日普通订单投注额；取消订单仍保留原始下单行为。'),amount('validStake','普通有效投注（结算日）','当日完成结算、未退款的普通订单投注额。'),
   amount('ordinaryPosted','普通返还到账净额','当日会员分录返还补发减追回；退款另列。'),amount('ordinaryProfit','普通已结算净输赢','当日已结算未退款订单的净返还减投注额。'),
   amount('aiPurchase','AI净参与积分','当日认购额减当日退回认购额，跨日退款在退款日形成负数。'),amount('aiPosted','AI返还到账','当日实际到账，包含本金。'),
   amount('rewardPosted','推广奖励净发放','固定奖励与AI推广奖励的实际发放减回收；不是应发义务。'),amount('refund','投注/认购退款','当日退回的普通投注及AI认购本金，和返还分开展示。')]},
 stationBusiness:{name:'站点站长经营报表(新增)',href:'/reports/station-business',pageId:'A32',purpose:'对比站点与站长的会员规模、积分流动、参与、返还与奖励，发现需要跟进的站点。',
  business:['可切换站点汇总与站长汇总。期间业务取发生时归属；当前会员数和余额取查询时归属，两类列明确分开，迁移不会重写历史业务。',
   '参与会员数在完整筛选区间去重；经营金额与经营日报共用记录。平台给站长的预算调整和站长给会员加减分属于不同业务。',...common],
  columns:[c('groupName','站点 / 站长'),c('stationName','所属站点'),c('memberCount','当前会员数',undefined,'查询时归属本组的会员数量，不是期间新增数。'),c('activeCount','期间参与会员数'),
   amount('available','当前会员可用积分','当前归属会员的可用积分快照；不是筛选期末余额。'),amount('reserved','当前会员冻结积分','当前归属会员冻结积分快照。'),
   amount('granted','期间会员加分净额','按操作时归属统计站长加分减冲正。'),amount('deducted','期间会员减分净额','按操作时归属统计减分减冲正。'),
   amount('ordinaryPurchase','期间普通下单积分','区间内下单积分。'),amount('validStake','期间普通有效投注','区间内完成结算且未退款的普通订单投注额。'),amount('ordinaryProfit','普通已结算净输赢','会员净输赢，不是平台现金利润。'),
   amount('aiPurchase','期间AI净参与积分','认购额减区间内退款。'),amount('aiPosted','期间AI返还到账','以会员实际到账分录和历史归属为准。'),amount('rewardPosted','期间推广净发放','奖励实际发放减回收。'),
   c('asOf','当前快照时间','time')]},
 budgetFlows:{name:'预算收支报表(新增)',href:'/finance/budget-flows',pageId:'A33',purpose:'核对平台四类预算与站长可用预算的收支，区分预算来源、内部拨付、返还和推广支出。',
  business:['账户分录与当前预算两个页签。流水只计平台预算主账户和站长预算账户，不纳入会员分录、预算来源对手账户或AI日额度。',
   '审批未通过的预算追加不计收入。原始交易和冲正按实际分录金额统计；内部拨付双方各有一条账户流水，全部账户收支不代表平台经营收入。',
   '当前预算页显示查询时余额和已留存期间收支。缺少完整开户余额与历史账本，不展示推算出的期初/期末余额。',...common],
  columns:[c('accountName','预算账户'),c('ownerType','账户归属','status'),c('budgetType','预算类别','status'),c('createdAt','发生时间','time'),c('stationName','所属站点'),c('stationMasterName','所属站长'),
   c('type','业务类型','status'),amount('delta','变动额','增加为正、减少为负。'),amount('before','变动前余额','本笔已留存分录余额；历史未记录不回填。'),amount('after','变动后余额','本笔分录余额。'),c('businessNumber','业务单号'),c('operatorName','操作人'),c('remark','备注')]},
 reconciliations:{name:'对账异常报表(新增)',href:'/finance/reconciliations',pageId:'A34',purpose:'查看每次对账的范围、预期、实测、差异账户和检查时间，并追溯异常分录。',
  business:['每行对应一次保存的对账快照，不把多次对账的余额相加。统计任务数、差异任务数、异常账户和绝对差异额。',
   '历史演示快照明确标记。新建本地模拟对账检查已留存分录的前后数值与借贷平衡；资料缺失显示资料不足，不代表完成真实数据库账户余额核对。',
   '检查结束时保存结果，刷新和后续预算变更不会改写旧快照；没有足够数据不填成零差异。',...common],
  columns:[c('businessNumber','对账编号'),c('scopeName','对账范围'),c('status','结果','status'),amount('expected','预期积分','本次范围内保存的预期值。'),amount('actual','实测积分','本次对账时的实测值。'),
   amount('difference','差异（实测−预期）','正数表示实测较多，负数表示实测较少。'),c('mismatchCount','差异项数'),c('missingCount','资料缺失项数'),c('createdAt','检查时间','time'),c('operatorName','发起人'),c('reason','异常说明')]},
 exceptions:{name:'异常待办报表(新增)',href:'/reports/exception-backlog',pageId:'A35',purpose:'集中跟进返还待到账、预算不足、计算失败、对账差异和预算审批，跳转原业务处理后刷新。',
  business:['从当前业务状态生成待办，不创建另一套处理状态。仅列需运营跟进的异常/审批，正常待开奖不列异常。',
   '处理顺序是运营建议：账务差异优先核对，待到账业务其次，审批待办另列。不是新增自动风控或强制时限。',
   '待发积分只汇总已形成的会员返还/奖励义务，审批预算金额和对账差异另计；不适用于该业务的列显示不适用。一个合买期次的异常与部分到账合并，避免重复统计。',
   '缺少首次异常发生时间显示未记录，参考业务时间不能当作真实故障起点。关联操作完成后，待办由当前状态自动更新。',
   '预算审批、全局对账和跨站合买属于平台级待办。会员/站点筛选只保留有对应归属的记录；查看平台级待办时保持所属筛选为空。',...common],
  columns:[c('businessNumber','业务单号'),c('type','待办类型','status'),c('priority','处理顺序（运营建议）','status'),c('memberAccount','相关会员'),c('stationName','所属站点'),c('stationMasterName','所属站长'),
   c('status','当前状态','status'),amount('pending','待发积分','仅会员返还/奖励待到账；不包括审批金额。'),amount('difference','账务差异','需要核对的对账差异。'),amount('approvalAmount','待审批预算','审批通过前不作为预算收入。'),
   c('createdAt','参考业务时间','time'),c('reason','原因'),c('nextAction','建议处理方式')]},
 aiBusiness:{name:'AI合买经营报表(修改)',href:'/ai-pools/reports',pageId:'A06',purpose:'按项目和期次分析会员参与、平台投入、返还分配与到账差异，补足原有AI经营报表。',
  business:['每行对应合买期次，参与人数从会员认购去重，参与次数取实际记录，退款认购不计有效人数。',
   '会员应返、实际到账、待发分别列出；应返与平台应得来自当前有效结算结果，未开奖不能当作零收益。会员收益率按已完成期次净返还/参与计算，汇总使用金额加权。',
   '平台应得减平台投入是期次分配口径，不等于预算实际到账或现金利润。所属站点/会员粒度在AI参与报表查看，不将平台资金重复分摊到会员行。',...common],
  columns:[c('projectName','合买项目'),c('issueCode','期号'),c('lotteryName','彩种'),c('status','结算状态','status'),c('participantCount','有效参与会员数'),c('participationCount','认购次数'),
   amount('purchase','会员有效参与积分','未退款认购合计。'),amount('platformPoints','平台投入积分','该期平台参与本金。'),amount('totalPurchase','实际总参与积分','会员有效参与加平台投入。'),
   amount('due','会员应返','当前有效结算结果，包含本金。'),amount('posted','会员实际到账','实际发放对象明细的净到账合计。'),amount('pending','会员待到账','已形成应返减实际到账的正数部分。'),
   amount('platformReturn','平台应得返还','本期总应返减会员应返，不代表平台预算已入账。'),amount('platformProfit','平台应得净收益','平台应得返还减平台投入，待开奖不计算。'),amount('profit','会员已结算净收益','仅全部发放完成后计算实际到账减有效认购。'),
   c('memberRate','会员已结算收益率','rate','已结算会员净收益/有效参与，汇总按积分加权，不平均行收益率。'),c('createdAt','期次创建时间','time'),c('postedAt','最近发放时间','time')]},
};
export const budgetSnapshotColumns:ReportColumn[]=[c('accountName','预算账户'),c('ownerType','账户归属','status'),c('budgetType','预算类别','status'),c('stationName','所属站点'),c('stationMasterName','所属站长'),amount('available','当前可用预算','查询时当前预算，不是筛选期末余额。'),amount('reserved','当前冻结预算','当前冻结预算，平台与站长账户分开。'),amount('inflow','已记录期间增加','所选区间内留存主账户收入分录。'),amount('outflow','已记录期间减少','区间内留存支出分录。'),amount('netFlow','已记录净变动','区间增加减减少。'),c('asOf','余额快照时间','time')];
