import { reportDefinitions, rewardColumns, type ReportKind } from './report-config';

export interface ModuleChange { name: string; href: string; summary: string; changes: string[]; fields: string[][]; business: string[]; functions?: string[]; }
const help: Record<string, string> = {
  memberAccount: '会员登录账号；推广页表示奖励接收人或推荐人。可搜索账号、名称，点击进入会员详情。',
  sourceMemberAccount: '触发推广奖励的直属会员账号，支持单独搜索；与奖励接收人分别展示。',
  stationName: '记录发生时所属站点；推荐关系页显示当前归属。按站点下拉筛选，并联动站长选项。',
  stationMasterName: '记录发生时所属站长；推荐关系页显示当前归属。按站长下拉筛选。',
  createdAt: '发生或生效时间，精确到秒，统一北京时间。AI 页支持按任一次认购时间筛选；推荐关系按绑定时间筛选。',
  operation: '本笔会员积分增加显示加分，减少显示减分。冲正方向与原单相反，另外标记冲正。',
  amount: '本笔积分变动的绝对值，可按金额上下限筛选。不是人民币金额。',
  operatorName: '实际操作员工、站长或系统；旧记录未保存身份时明确显示未记录。可按关键词查询。',
  businessNumber: '稳定业务单号或订单号，按文本显示与导出；可通过关键词搜索，并在详情追溯。',
  before: '本笔会员分录变动前数值；日额度表示当时剩余日额度。未留存的历史数值显示未记录。',
  after: '本笔会员分录变动后数值，可用金额上下限筛选；不使用会员当前余额回填旧记录。',
  delta: '增加为正、减少为负，支持含负数的上下限筛选。积分与 AI 日额度分开统计。',
  accountType: '积分账户·可用积分、积分账户·冻结积分或 AI 合买日额度，支持账户下拉筛选。',
  type: '具体账变或奖励类型，含加减分、冲正、投注返还、推广奖励、额度占用与释放等；下拉筛选。',
  remark: '操作原因或备注，只读；可按关键词筛选。',
  reversal: '区分原始记录、有冲正的原单及冲正记录；详情关联原单与每笔冲正。',
  sourceName: '引起本次变动的业务名称，详情可跳转关联会员、订单、合买或奖励。',
  projectName: 'AI 合买长期项目名称，支持按项目筛选。',
  issueCode: '彩票或合买期次编号，按文本保存，支持期号搜索。',
  purchase: '有效认购或订单参与使用的虚拟积分；AI 已退款认购从有效参与积分中扣除。',
  drawStatus: '是否已有开奖信息，独立于是否发放；已开奖且未中奖也是已开奖。',
  posted: '净到账返还或净已发奖励；推广奖励为发放减回收，AI 返还包含本金。',
  postedAt: '最近一次实际到账或奖励发放时间；尚未发放显示尚未发放。',
  lastParticipationAt: '该会员该期最近一次认购的时间，展开可查看每次参与明细。',
  participationCount: '同会员同一期认购次数；取消认购也留痕，金额按有效认购汇总。',
  due: '当前结算应返积分；未形成可信结果显示待开奖或待结算，不能填成 0。',
  profit: '仅完成结算且有效记录计算净到账返还减参与积分。未结算、退款、正在更正不计入已结算输赢。',
  pending: '已形成应返或应发、尚未到账的正数部分。待开奖的未知应返不计入金额汇总。',
  refundPoints: '退回的参与积分，和返还、奖励分开展示；详情列出追回返还与退款时间。',
  participationStatus: '认购中、已锁定、已结算或已取消并退款，保留逐次认购历史。',
  status: '业务状态或等级变更类型，中文显示，可在适用页面下拉筛选。',
  level: '推荐关系取当前推广等级；奖励明细取产生奖励时的历史等级快照。',
  directCount: '当前第一层直属会员数，不包含间接下级；点击查看完整会员账号名单。',
  validCount: '启用且累计有效加分达到当前推广门槛的直属会员数，点击查看有效名单。',
  fixedPosted: '固定推广奖励累计净已发积分，不含 AI 推广分红。',
  aiPosted: 'AI 推广分红累计净已发积分，资金来自平台推广预算。',
  targetDue: '扣除更正后的目标应发奖励净额；应发与已发分开记录。',
  recovered: '更正或撤销追回的奖励累计金额，已发净额已扣除此值，不再重复扣减。',
  basis: '固定奖励对应有效加分门槛；AI 推广分红对应来源会员正净返还收益。',
  rate: '产生奖励时锁定的 AI 推广比例，按百分比显示；固定奖励没有比例。',
  policyVersion: '奖励形成时政策版本，后续修改配置不会回写历史。',
  qualifiedPoints: '累计有效站长加分减对应加分冲正，是 VIP 升级依据，积分保留两位小数。',
  validStakePoints: '变更前已完成结算且未退款普通订单的投注积分，是运营分析项。',
  beforeLevel: '本次等级变化前的等级，即本次初始等级。',
  afterLevel: '本次变更后等级，可展示升级、跨级或降级。',
  threshold: '本次变更目标等级的有效加分门槛，取历史配置快照。',
  beforeQuota: '变更前 VIP 基础日额度；不包含单独的推广附加额度。',
  afterQuota: '变更后 VIP 基础日额度；等级与额度都保留历史快照。',
  reason: '等级变更、业务操作或退款原因，只读展示。',
  ruleVersion: '记录生效时规则版本，不自动生成产品版本号。',
  lotteryName: '订单彩票名称，支持彩种筛选，详情展示投注号码及开奖信息。',
  playName: '订单玩法名称，玩法选项随彩种联动。',
  settledAt: '订单实际完成结算时间；待结算或历史未留存时显示未记录。',
};
export const operationalChanges: Record<ReportKind, ModuleChange> = Object.fromEntries(Object.entries(reportDefinitions).map(([key, definition]) => [key, {
  name: definition.name, href: definition.href, summary: definition.purpose,
  changes: ['新增左侧菜单入口、报表列表、会员/站点/站长/时间筛选、全筛选统计和 CSV/XLSX 导出。',
    '默认每页10条，支持10/20/40/60/80/100条、并排页码、末页及下拉即时跳页；会员账号和操作列冻结。',
    '新增可追溯详情与关联业务跳转，说明和当前版本汇总共用同一份内容。'],
  fields: [...definition.columns, ...(key === 'referrals' ? rewardColumns : [])].filter((c, i, all) => all.findIndex(x => x.key === c.key) === i)
    .map(c => [c.label, help[c.key] || '只读演示字段，详情保留业务来源；历史缺失明确显示未记录。']),
  business: definition.business,
  functions: ['查询与重置；秒级时间区间；站点与站长联动；适用页面的状态、类型、金额区间筛选。',
    '完整筛选结果汇总；10条默认分页；下拉选页立即跳转；导出完整筛选结果并点击下载链接保存。',
    '查看详情；点击会员账号及关联业务；缺失历史、待开奖、待发放与空结果提示。',
    ...(key === 'referrals' ? ['推荐关系与奖励明细切换；点击推广会员数或有效会员数查看对应账号名单。'] : []),
    ...(key === 'vip' ? ['仅升级与全部等级变更切换，查看跨级、降级和历史额度。'] : [])],
}])) as Record<ReportKind, ModuleChange>;

export const linkedChanges: Record<string, ModuleChange> = {
  aiManagement: { name: 'AI合买(修改)', href: '/ai-pools', summary: '认购绑定会员，模拟发放按实际参与人及参与积分形成明细，并同步参与报表与推广奖励义务。',
    changes: ['认购列表使用持久化本地记录；发放明细绑定会员并保存到账时间；部分发放重试只补足未发金额。'],
    fields: [['会员关联 / 到账时间', '本地认购及发放记录补齐会员关联和实际操作时间；历史未记录的交易引用显示未记录。']],
    business: ['同一会员多次认购合并计算返还，推广收益使用锁定的直属关系与比例；相关报表读取同一份本地记录。'], functions: ['认购查看、模拟发放、重试及参与报表跳转。'] },
  orders: { name: '普通参与订单(修改)', href: '/orders', summary: '保留本地订单结算、更正和退款明细；恢复结算任务后同步会员投注记录。',
    changes: ['模拟结算完成时保存真实本地操作时间、结算记录和交易引用；订单详情读取同一份历史。'],
    fields: [['结算 / 更正 / 退款历史', '沿用订单字段，补充本地历史与完成时间；未知历史显示未记录。']],
    business: ['待结算不计输赢，退款与追回单独展示；恢复任务仅补足未到账返还。'], functions: ['订单详情、结算重试、投注报表跳转。'] },
  ledger: { name: '积分账本与对账(修改)', href: '/ledger', summary: '冲正按本次数额生成分录并更新相关本地积分；关联会员帐变可追溯原单。',
    changes: ['部分冲正按实际冲正金额生成前后余额和关联分录；保存操作人及操作时间。'],
    fields: [['冲正金额 / 原单引用 / 前后余额', '只读显示本次变动，冲正累计不超过原交易可冲正额；详情保留原单和对应冲正。']],
    business: ['不复制原单全额作为部分冲正；会员与对手分录平衡，相关本地记录同步。'], functions: ['原单查看、冲正、会员帐变跳转。'] },
  qualifications: { name: 'VIP与推广配置(修改)', href: '/members/vip', summary: '本地资格重算按有效加分和有效直属会员匹配等级，并保留等级变化历史。',
    changes: ['本地资格重算更新当前等级和日额度，等级变化写入历史报表。'],
    fields: [['等级 / 额度历史快照', '记录变更前后等级、有效加分、门槛、AI基础日额度、规则版本和生效时间。']],
    business: ['VIP 以有效站长加分升级，推广等级按启用且达到加分门槛的直属会员数量匹配；历史奖励不回写。'], functions: ['配置查看与调整、资格重算、VIP升级记录跳转。'] },
};
