import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as operations from '../src/features/operations/operations-api';
import * as robots from '../src/features/robots/robots-api';
import * as members from '../src/features/member-management/member-api';
import * as stations from '../src/features/station-management/station-management-api';
import * as ai from '../src/features/ai-management/ai-management-api';
import * as orders from '../src/features/order-management/order-api';
import * as ledger from '../src/features/ledger-management/ledger-api';
import * as employees from '../src/features/employee-security/employee-api';
import { state, points } from '../src/demo/state';
import { adminApi } from '../src/lib/api';
import { refreshMemberMetrics } from '../src/demo/member-metrics';

globalThis.fetch=(()=>{throw new Error('Prototype attempted a network request');}) as typeof fetch;
const results:{name:string;passed:boolean;error?:string}[]=[];
async function check(name:string,action:()=>Promise<unknown>){try{await action();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:String(e)});}}
const l=state.catalog.lotteries[0],r=state.robots[0],member=state.members[0],master=state.stationMasters[0],pool=state.pools[1];
await check('目录 / 8 彩种 / 22 玩法',async()=>{const c=await operations.getAdminCatalog();assert.equal(c.lotteries.length,8);assert.equal(c.lotteries.flatMap(l=>l.plays).length,22);});
await check('期次',()=>operations.listIssues(l.id));
await check('规则详情',()=>operations.getRuleDetail(l.plays[0].id));
await check('数据健康',()=>operations.getDataHealth());
await check('数据来源',()=>operations.listDataSources());
await check('规则版本',()=>operations.listRuleDrafts());
await check('政策版本',()=>operations.listPolicies());
await check('开奖候选',()=>operations.listDrawCandidates(l.id,'2026261'));
await check('开奖版本',()=>operations.listDrawVersions(l.id,'2026260'));
await check('遗漏缺口',()=>operations.listOmissionGaps(state.catalog.lotteries[5].id));
await check('大师策略',()=>robots.listRobotStrategies());
await check('大师列表 / 48 头像',async()=>{const page=await robots.listAdminRobots({limit:100});assert.equal(page.items.length,48);});
await check('大师详情',()=>robots.getAdminRobot(r.robot.id));
await check('大师执行',()=>robots.listRobotExecutions(r.robot.id));
await check('大师推荐',()=>robots.listAdminRecommendations(r.robot.id));
await check('站点',()=>stations.listStations({}));
await check('站点详情',()=>stations.getStation(state.stations[0].id));
await check('站长',()=>stations.listStationMasters({}));
await check('站长详情',()=>stations.getStationMaster(master.id));
await check('会员列表',()=>members.listAdminMembers({}));
await check('会员 125 条 / 五档分页 / 首尾边界 / 筛选',async()=>{
  const original=state.members;
  try {
    state.members=Array.from({length:125},(_,i)=>({...structuredClone(original[i%original.length]),id:`pagination-member-${i+1}`,account:`pagination_${i+1}`,displayName:`分页验收${i+1}`}));
    assert.equal((await members.listAdminMembers({})).items.length,20);
    for(const limit of [20,40,60,80,100]){
      const seen:string[]=[];let cursor:string|undefined;
      do {
        const result=await members.listAdminMembers({limit,cursor});
        assert.equal(result.totalCount,125);
        assert.equal(result.items.length,Math.min(limit,125-seen.length));
        seen.push(...result.items.map(item=>item.id));
        assert.equal(result.hasMore,seen.length<125);
        cursor=result.nextCursor??undefined;
      } while(cursor);
      assert.equal(new Set(seen).size,125);
      assert.deepEqual(seen,state.members.map(item=>item.id));
    }
    const filtered=await members.listAdminMembers({stationId:state.stations[0].id,limit:20});
    assert.equal(filtered.totalCount,42);assert.equal(filtered.items.length,20);
    assert.equal((await members.listAdminMembers({stationId:state.stations[0].id,limit:20,cursor:'40'})).items.length,2);
    const empty=await members.listAdminMembers({keyword:'没有此会员'});
    assert.equal(empty.totalCount,0);assert.equal(empty.nextCursor,null);assert.equal(empty.hasMore,false);
  } finally {state.members=original;}
});
await check('积分公式 / 负净收益 / 冻结单列 / AI 三项额度',async()=>{
  const row={...structuredClone(member),qualifiedRechargePoints:'1000.10',totalReferralPoints:'80.20',netProfitPoints:'-120.30',aiDividendPoints:'40.05',stationDeductedPoints:'200.10'};
  row.wallet.reservedPoints='500.00';row.quota.totalLimit='1200.00';row.quota.usedPoints='123.45';
  refreshMemberMetrics([row]);
  assert.equal(row.wallet.availablePoints,'799.95');assert.equal(row.wallet.reservedPoints,'500.00');assert.equal(row.quota.remainingPoints,'1076.55');
});
await check('直属与三级下级汇总 / 归属变更 / 不受分页影响',async()=>{
  const original=state.members;
  try {
    const parentIds=[null,'tree-0','tree-0','tree-1','tree-3'];
    state.members=parentIds.map((parentId,i)=>({...structuredClone(member),id:`tree-${i}`,qualifiedRechargePoints:String((i+1)*100)+'.00',totalReferralPoints:'0.00',netProfitPoints:'0.00',aiDividendPoints:'0.00',stationDeductedPoints:'0.00',scope:{...structuredClone(member.scope),referrerMember:parentId?{id:parentId,code:parentId,name:parentId}:null}}));
    const root=(await members.listAdminMembers({keyword:'tree-0',limit:1})).items[0];
    assert.equal(root.directMemberCount,2);assert.equal(root.descendantMemberCount,4);
    assert.equal(root.directMemberAvailableTotal,'500.00');assert.equal(root.descendantMemberAvailableTotal,'1400.00');
    const leaf=(await members.getAdminMember('tree-4')).data;
    assert.equal(leaf.descendantMemberCount,0);assert.equal(leaf.descendantMemberAvailableTotal,'0.00');
    state.members[3].scope.referrerMember=null;
    const moved=(await members.getAdminMember('tree-0')).data;
    assert.equal(moved.descendantMemberCount,2);assert.equal(moved.descendantMemberAvailableTotal,'500.00');
  } finally {state.members=original;}
});
await check('旧本地数据补齐 / AI 历史发放 / 邀请码稳定',async()=>{
  const old=structuredClone(member);delete old.aiDividendPoints;delete old.totalReferralPoints;delete old.inviteCode;
  old.status='DISABLED';old.displayName='保留已有演示修改';
  refreshMemberMetrics([old],[{memberId:old.id,type:'AI_AWARD',economicPoints:'12.34',reversedPoints:'0.00'}]);
  assert.equal(old.aiDividendPoints,'12.34');assert.equal(old.totalReferralPoints,'0.00');
  assert.equal(old.status,'DISABLED');assert.equal(old.displayName,'保留已有演示修改');
  const code=old.inviteCode;refreshMemberMetrics([old]);assert.equal(old.inviteCode,code);assert.equal(old.aiDividendPoints,'12.34');
});
await check('会员详情',()=>members.getAdminMember(member.id));
await check('会员流水',()=>members.listAdminMemberLedgers(member.id));
await check('会员订单',()=>members.listAdminMemberOrders(member.id));
await check('VIP 配置',()=>members.getVipConfig());
await check('VIP 版本',()=>members.listVipConfigHistory());
await check('推广配置',()=>members.getReferralConfig());
await check('推广版本',()=>members.listReferralConfigHistory());
await check('AI 项目',()=>ai.listProjects());
await check('AI 项目详情',()=>ai.getProject(pool.projectId));
await check('AI 设置',()=>ai.getProjectConfig(pool.projectId));
await check('AI 50x20 组合',async()=>{const p=await ai.getCombinationPreview(pool.projectId);assert.equal(p.combinations.length,50);assert.equal(new Set(p.combinations.flatMap(c=>c.numberCodes)).size,1000);});
await check('AI 期次',()=>ai.listPools(pool.projectId));
await check('AI 期次详情',()=>ai.getPool(pool.id));
await check('AI 认购',()=>ai.listSubscriptions(pool.id));
await check('AI 分配历史',()=>ai.listAllocations(pool.id));
await check('AI 分配详情',()=>ai.getAllocation(state.allocations[0].id));
await check('AI 发放进度',()=>ai.getSettlementExecution(pool.id));
await check('订单列表',()=>orders.listAdminOrders({}));
await check('订单详情',()=>orders.getAdminOrder(state.orders[0].id));
await check('双边积分账本',()=>ledger.listAdminLedgerTransactions({}));
await check('预算账户',()=>ledger.listBudgets());
await check('员工',()=>employees.listEmployees());
await check('角色权限',()=>employees.listRoles());
await check('审计',()=>employees.listAudits({}));
for(const type of ['MEMBER_OVERVIEW','MEMBER_POINTS','VIP_LEVELS','REFERRAL_LEVELS','AI_QUOTA','AI_POOLS','STATION_MASTERS','LEDGER_RECONCILIATION'])await check(`报表 ${type}`,()=>operations.getAdminReport(type as any,{from:'2026-09-27',to:'2026-10-03'}));
await check('新增站点 / 更新 / 停用',async()=>{const created=(await adminApi.request<any>('/api/admin/v1/stations',{method:'POST',body:{code:'TEST',name:'验收站点',regionLabel:'杭州',remark:'demo'}})).data;assert.equal((await stations.getStation(created.id)).value.name,'验收站点');await adminApi.request(`/api/admin/v1/stations/${created.id}/status`,{method:'POST',body:{status:'DISABLED',reason:'验收'}});assert.equal((await stations.getStation(created.id)).value.status,'DISABLED');});
await check('会员停用 / 恢复',async()=>{const v=await members.getAdminMember(member.id);const updated=await members.setMemberStatus({memberId:member.id,status:'DISABLED',reason:'演示验收',etag:v.etag,idempotencyKey:'verify-member'});assert.equal(updated.data.status,'DISABLED');await members.setMemberStatus({memberId:member.id,status:'ENABLED',reason:'恢复',etag:updated.etag,idempotencyKey:'verify-member-restore'});});
await check('大师新增 / 编辑 / 删除',async()=>{const created=await robots.createRobot({name:'验收大师',allowedLotteryIds:[l.id],strategy:r.strategy,generationMode:'MANUAL',generationTime:null,reason:'demo'},'verify-robot');assert.equal(created.robot.lotteryIds[0],l.id);await robots.deleteRobot(created,'验收删除','verify-delete');});
await check('AI 重算 → 确认 → 公示 → 发放 → 进度',async()=>{const first=await ai.getAllocation(state.allocations[0].id);const preview=await ai.recalculateAllocation({allocation:first.value,targetNetReturnPercent:15,reason:'演示验收',etag:first.etag!,idempotencyKey:'verify-allocation'});const confirmed=await ai.confirmAllocation({allocationId:preview.id,reason:'演示确认',etag:'"2"',idempotencyKey:'verify-confirm'});assert.equal(confirmed.confirmationStatus,'CONFIRMED');const disclosure=await ai.publishDisclosure({poolIssueId:pool.id,allocation:confirmed,reason:'演示公示',idempotencyKey:'verify-publish'});const prep=await ai.preparePayout({poolIssueId:pool.id,allocationVersion:confirmed.version,disclosureVersion:disclosure.version,expectedInputVersionSetHash:confirmed.inputVersionSetHash,idempotencyKey:'verify-prep'});assert.equal(prep.eligible,true);const accepted=await ai.submitPayout({poolIssueId:pool.id,preparationId:prep.preparationId,confirmText:'确认发放',idempotencyKey:'verify-payout'});const completed=await ai.getTask(accepted.taskId);assert.equal(completed.status,'SUCCEEDED');assert.equal(completed.progress,1);assert.ok(accepted.statusUrl.includes('/payout-batches/'));assert.equal((await ai.getPayout(accepted.statusUrl.split('/').at(-1)!)).status,'COMPLETED');const execution=await ai.getSettlementExecution(pool.id);assert.ok(execution.payoutBatchId);const batch=await ai.getPayout(execution.payoutBatchId!);assert.equal(batch.status,'COMPLETED');const items=await ai.listPayoutItems(batch.id);assert.ok(items.items.every(item=>state.ledgers.some(tx=>tx.id===item.transactionId)));assert.equal(items.items.reduce((sum,item)=>sum+Number(item.postedPoints),0),Number(batch.postedPoints));assert.equal((await ai.getPool(pool.id)).value.pool.status,'SETTLED');});
await check('AI 分红与可用积分到账联动 / 列表详情一致',async()=>{
  const detail=(await members.getAdminMember(member.id)).data;
  assert.equal(detail.aiDividendPoints,'215.00');assert.equal(detail.netProfitPoints,'50.00');
  assert.equal(detail.totalReferralPoints,'550.00');assert.equal(detail.wallet.availablePoints,'2715.00');
  const list=(await members.listAdminMembers({limit:20})).items.find(item=>item.id===member.id)!;
  assert.equal(list.aiDividendPoints,detail.aiDividendPoints);assert.equal(list.wallet.availablePoints,detail.wallet.availablePoints);
  assert.equal(detail.directMemberAvailableTotal,points(state.members.slice(1).reduce((sum,item)=>sum+Number(item.wallet.availablePoints),0)));
});
await check('上传仅在本地解析',async()=>{const result=await operations.uploadEvidence(new File(['{"demo":true}'],'demo.json',{type:'application/json'}),'DRAW_EVIDENCE',{prepare:'p',commit:'c'});assert.equal(result.status,'COMMITTED');});
await check('导出生成及读取',async()=>{const result=(await adminApi.request<any>('/api/admin/v1/report-exports',{method:'POST',body:{reportType:'MEMBER_OVERVIEW',format:'CSV',filters:{from:'2026-09-27',to:'2026-10-03'}}})).data;assert.ok(result.statusUrl.includes('/report-exports/'));const item=(await adminApi.request<any>(result.statusUrl)).data;assert.ok(item.downloadUrl.startsWith('blob:'));});
await check('上海日期筛选保留当天账本',async()=>{const rows=await ledger.listAdminLedgerTransactions({from:'2026-10-02T16:00:00Z',to:'2026-10-03T15:59:59Z'});assert.ok(rows.items.length>=12);assert.ok(rows.items.some(t=>t.id==='demo-transaction-1'));});
await check('空筛选 / 重置 / 分页',async()=>{assert.equal((await members.listAdminMembers({keyword:'不存在的会员'})).items.length,0);const first=await robots.listAdminRobots({limit:20});const second=await robots.listAdminRobots({limit:20,cursor:first.nextCursor!});assert.equal(second.items.length,20);assert.notEqual(first.items[0].robot.id,second.items[0].robot.id);});
await check('新增站长及初始额度',async()=>{const created=await stations.createStationMaster({clientIntentId:'verify',name:'验收站长',account:'demo_new',initialPassword:'DemoOnly123',stationId:state.stations[0].id,status:'ENABLED',limits:master.limits,initialDisposablePoints:'1000.00',remark:'演示验收'},'verify-master');assert.equal(created.disposablePoints,'1000.00');assert.ok(created.code);});
await check('站长额度调整及账本联动',async()=>{const before=Number(master.disposablePoints),count=state.ledgers.length;const received=await stations.adjustStationMasterPoints({stationMaster:master,type:'ADMIN_GRANT',points:'500.00',reason:'演示验收',proofCode:'123456',idempotencyKey:'verify-grant'});assert.equal(Number(received.stationMasterBalanceAfter),before+500);assert.equal(state.ledgers.length,count+1);assert.equal((await stations.listAdminStationLedgers({stationMasterId:master.id})).items[0].transactionId,received.transactionId);});
await check('站长迁移',()=>stations.migrateStationMaster({stationMaster:master,targetStationId:state.stations[1].id,moveOwnedMembers:true,reason:'演示验收',proofCode:'123456',etag:'"1"',idempotencyKey:'verify-migrate'}));
await check('会员纠正归属',()=>members.migrateMembership({member,stationId:state.stations[2].id,stationMasterId:state.stationMasters[2].id,referrerMemberId:null,reason:'演示验收',proofCode:'123456',etag:'"1"',idempotencyKey:'verify-membership'}));
await check('VIP 整表保存与历史',async()=>{const v=await members.getVipConfig();const saved=await members.saveVipConfig({levels:v.data.levels,reason:'验收',etag:v.etag,idempotencyKey:'verify-vip'});assert.notEqual(saved.data.version,v.data.version);assert.equal((await members.listVipConfigHistory()).items.length,2);});
await check('推广整表保存与历史',async()=>{const v=await members.getReferralConfig();await members.saveReferralConfig({levels:v.data.levels,fixedRewardPolicyVersion:'2',aiSharePolicyVersion:'2',reason:'验收',etag:v.etag,idempotencyKey:'verify-referral'});assert.equal((await members.getReferralConfig()).data.fixedRewardPolicyVersion,'2');});
await check('资格重建',()=>members.rebuildQualifications({reason:'演示验收',idempotencyKey:'verify-qualification'}));
await check('会员报表解析',()=>members.getMemberReport('MEMBER_OVERVIEW',{from:'2026-09-27',to:'2026-10-03'}));
await check('AI 报表解析',()=>ai.getAiReport({from:'2026-09-27',to:'2026-10-03'}));
await check('站长报表解析',()=>stations.getStationMasterReport({filters:{from:'2026-09-27',to:'2026-10-03'}}));
await check('对账报表解析',()=>ledger.getAdminReport({from:'2026-09-27',to:'2026-10-03'}));
await check('新建员工及权限更新',async()=>{const employee=await employees.createEmployee({clientIntentId:'verify-employee',name:'验收员工',account:'demo_staff',initialPassword:'DemoOnly123',roleIds:[state.roles[0].id],scopeStationIds:[],reason:'演示验收',proofCode:'123456',idempotencyKey:'verify-employee'});assert.equal(employee.account,'demo_staff');const updated=await employees.updateEmployeePermissions({employee,roleIds:[state.roles[1].id],scopeStationIds:[state.stations[0].id],reason:'演示验收',proofCode:'123456',idempotencyKey:'verify-permission'});assert.equal(updated.scopeStationIds.length,1);});
await check('员工恢复',()=>employees.recoverEmployeeAccount({employee:state.employees[1],newPassword:'DemoOnly123',evidenceId:'demo-evidence',reason:'演示验收',proofCode:'123456',idempotencyKey:'verify-recovery'}));
await check('账本冲正',()=>ledger.createLedgerReversal({originalTransactionId:state.ledgers[0].id,points:'100.00',reason:'演示验收',evidenceIds:['demo-evidence'],proofCode:'123456',idempotencyKey:'verify-reversal'}));
await check('发起对账并读取结果',async()=>{const accepted=await ledger.createReconciliation({reason:'演示验收',idempotencyKey:'verify-reconciliation'});const status=await ledger.getAdminTask(accepted.taskId);const id=status.resultUrl!.split('/').at(-1)!;assert.equal((await ledger.getReconciliation(id)).status,'MATCHED');});
await check('普通订单恢复结算及会员账本联动',async()=>{const before=Number(member.wallet.availablePoints);await orders.retryOrdinarySettlement({orderId:state.orders[0].id,reason:'演示验收',idempotencyKey:'verify-settlement'});assert.equal(Number(member.wallet.availablePoints),before+50);assert.equal(state.ledgers[0].sourceId,state.orders[0].id);});
await check('规则提交及独立复核',async()=>{const row=await operations.createRuleDraft({playId:l.plays[0].id,artifact:{id:'demo-artifact',sha256:'demo-hash',status:'COMMITTED',purpose:'RULE_ARTIFACT'},effectiveFromIssue:'2026270',reason:'演示验收',idempotencyKey:'verify-rule'} as any);assert.equal(row.status,'PENDING_REVIEW');const existing=await operations.listRuleDrafts();const pending=existing.items.find(r=>r.id==='demo-rule-pending')!;const reviewed=await operations.reviewRuleDraft({rule:pending,decision:'APPROVE',reason:'演示验收',proofCode:'123456',idempotencyKey:'verify-rule-review'} as any);assert.equal(reviewed.status,'APPROVED');});
await check('政策登记',()=>operations.createPolicyVersion({code:'REFERRAL_FIXED',artifact:{id:'demo-policy',sha256:'demo-hash',status:'COMMITTED',purpose:'POLICY_ARTIFACT'},reason:'演示验收',idempotencyKey:'verify-policy'} as any));
await check('开奖复核',()=>operations.reviewDrawCandidate({candidate:state.candidates[0],decision:'APPROVE',reason:'演示验收',proofCode:'123456',idempotencyKey:'verify-draw'} as any));
await check('遗漏重建',()=>operations.rebuildOmissions({lotteryId:l.id,drawVersionSetHash:'demo-draw-hash',reason:'演示验收',idempotencyKey:'verify-omission'} as any));
await check('大师试算与执行更新',()=>robots.previewRobot({robotId:r.robot.id,lotteryId:l.id,issueCode:'2026261',reason:'演示验收',idempotencyKey:'verify-preview'}));
await check('AI 配置保存',async()=>{const v=await ai.getProjectConfig(pool.projectId);const saved=await ai.saveProjectConfig({projectId:pool.projectId,settings:{...v.config.settings,defaultTargetNetReturnPercent:20},reason:'演示验收',etag:v.etag!,idempotencyKey:'verify-ai-config'});assert.equal(saved.settings.defaultTargetNetReturnPercent,20);});
await check('AI 截止认购与生成分配',async()=>{const p=state.pools[0];await ai.closeFunding({poolIssueId:p.id,reason:'演示验收',etag:'"1"',idempotencyKey:'verify-close'});const v=await ai.getPool(p.id);const accepted=await ai.calculateAllocation({pool:v.value,reason:'演示验收',targetNetReturnPercent:10,idempotencyKey:'verify-calculate',etag:v.etag!} as any);assert.ok(accepted.taskId);});
await check('AI 人工一键结算',async()=>{const e=await ai.settleNow({poolIssueId:state.pools[4].id,targetNetReturnPercent:12,reason:'演示验收',etag:'"1"',idempotencyKey:'verify-quick'});assert.ok(e.payoutBatchId);});
await check('未知演示操作明确报错',async()=>{await assert.rejects(()=>adminApi.request('/api/admin/v1/undefined-feature'),/未映射/);});
await check('演示状态不存储密码',async()=>{assert.equal(JSON.stringify(state).includes('DemoOnly123'),false);});
fs.writeFileSync('evidence/verification.json',JSON.stringify({passed:results.filter(r=>r.passed).length,total:results.length,results},null,2));
for(const result of results)if(!result.passed)console.log('FAIL',result.name,result.error);
console.log(`${results.filter(r=>r.passed).length}/${results.length} checks passed; network forbidden throughout.`);
if(results.some(r=>!r.passed))process.exitCode=1;
